# Generated by Django 3.2.6 on 2023-06-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_acc',
            field=models.CharField(max_length=45, unique=True, verbose_name='Телеграм аккаунт'),
        ),
    ]
