# Generated by Django 3.2.6 on 2023-06-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_alter_user_telegram_acc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_acc',
            field=models.CharField(blank=True, help_text='Введите telegram username, например @user.\n Для того чтобы пользоваться ботом', max_length=45, unique=True, verbose_name='Телеграм аккаунт'),
        ),
    ]
